version: "3.8"

services:
  messages-redis:
    image: redis:7
    command: --requirepass ${REDIS_PASSWORD}
    networks:
      - prod-mynetwork
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    env_file:
      - ./.env

  postgres-db:
    image: postgres:16
    networks:
      - prod-mynetwork
    ports:
      - ${MSGSQLDB_PORT}:${MSGSQLDB_PORT}
    environment:
      POSTGRES_DB: ${MSGSQLDB_DATABASE}
      POSTGRES_USER: ${MSGSQLDB_USER}
      POSTGRES_PASSWORD: ${MSGSQLDB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/docker_volume/postgres:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./.env

  mongodb:
    image: mongo:7
    networks:
      - prod-mynetwork
    ports:
      - "${MSGMONGODB_PORT}:${MSGMONGODB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MSGMONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MSGMONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MSGMONGODB_ROOT_PASSWORD}
      MSGMONGODB_MESSAGES_USERNAME=: ${MSGMONGODB_MESSAGES_USERNAME}
      MSGMONGODB_MESSAGES_PASSWORD=: ${MSGMONGODB_MESSAGES_PASSWORD}
    volumes:
      - MSGMONGODB_data:/data/db
      - ./scripts/docker_volume/mongo:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./.env

volumes:
  redis_data:
  postgres_data:
  MSGMONGODB_data:

networks:
  prod-mynetwork:
